# TODO: prepare pngs for image_day and image_night
data_source:
  jma:
    default_none_string: データなし
    day_night_threshold: '17:00:00+09:00'
    weather_code:
      '100': {weather: '晴', image_day: './image/data_source/jma/100.png', image_night: './image/data_source/jma/500.png'}
      '101': {weather: '晴時々曇', image_day: './image/data_source/jma/101.png', image_night: './image/data_source/jma/501.png'}
      '102': {weather: '晴一時雨', image_day: './image/data_source/jma/102.png', image_night: './image/data_source/jma/502.png'}
      '103': {weather: '晴時々雨', image_day: './image/data_source/jma/102.png', image_night: './image/data_source/jma/502.png'}
      '104': {weather: '晴一時雪', image_day: './image/data_source/jma/104.png', image_night: './image/data_source/jma/504.png'}
      '105': {weather: '晴時々雪', image_day: './image/data_source/jma/104.png', image_night: './image/data_source/jma/504.png'}
      '106': {weather: '晴一時雨か雪', image_day: './image/data_source/jma/102.png', image_night: './image/data_source/jma/502.png'}
      '107': {weather: '晴時々雨か雪', image_day: './image/data_source/jma/102.png', image_night: './image/data_source/jma/502.png'}
      '108': {weather: '晴一時雨か雷雨', image_day: './image/data_source/jma/102.png', image_night: './image/data_source/jma/502.png'}
      '110': {weather: '晴後時々曇', image_day: './image/data_source/jma/110.png', image_night: './image/data_source/jma/510.png'}
      '111': {weather: '晴後曇', image_day: './image/data_source/jma/110.png', image_night: './image/data_source/jma/510.png'}
      '112': {weather: '晴後一時雨', image_day: './image/data_source/jma/112.png', image_night: './image/data_source/jma/512.png'}
      '113': {weather: '晴後時々雨', image_day: './image/data_source/jma/112.png', image_night: './image/data_source/jma/512.png'}
      '114': {weather: '晴後雨', image_day: './image/data_source/jma/112.png', image_night: './image/data_source/jma/512.png'}
      '115': {weather: '晴後一時雪', image_day: './image/data_source/jma/115.png', image_night: './image/data_source/jma/515.png'}
      '116': {weather: '晴後時々雪', image_day: './image/data_source/jma/115.png', image_night: './image/data_source/jma/515.png'}
      '117': {weather: '晴後雪', image_day: './image/data_source/jma/115.png', image_night: './image/data_source/jma/515.png'}
      '118': {weather: '晴後雨か雪', image_day: './image/data_source/jma/112.png', image_night: './image/data_source/jma/512.png'}
      '119': {weather: '晴後雨か雷雨', image_day: './image/data_source/jma/112.png', image_night: './image/data_source/jma/512.png'}
      '120': {weather: '晴朝夕一時雨', image_day: './image/data_source/jma/102.png', image_night: './image/data_source/jma/502.png'}
      '121': {weather: '晴朝の内一時雨', image_day: './image/data_source/jma/102.png', image_night: './image/data_source/jma/502.png'}
      '122': {weather: '晴夕方一時雨', image_day: './image/data_source/jma/112.png', image_night: './image/data_source/jma/512.png'}
      '123': {weather: '晴山沿い雷雨', image_day: './image/data_source/jma/100.png', image_night: './image/data_source/jma/500.png'}
      '124': {weather: '晴山沿い雪', image_day: './image/data_source/jma/100.png', image_night: './image/data_source/jma/500.png'}
      '125': {weather: '晴午後は雷雨', image_day: './image/data_source/jma/112.png', image_night: './image/data_source/jma/512.png'}
      '126': {weather: '晴昼頃から雨', image_day: './image/data_source/jma/112.png', image_night: './image/data_source/jma/512.png'}
      '127': {weather: '晴夕方から雨', image_day: './image/data_source/jma/112.png', image_night: './image/data_source/jma/512.png'}
      '128': {weather: '晴夜は雨', image_day: './image/data_source/jma/112.png', image_night: './image/data_source/jma/512.png'}
      '130': {weather: '朝の内霧後晴', image_day: './image/data_source/jma/100.png', image_night: './image/data_source/jma/500.png'}
      '131': {weather: '晴明け方霧', image_day: './image/data_source/jma/100.png', image_night: './image/data_source/jma/500.png'}
      '132': {weather: '晴朝夕曇', image_day: './image/data_source/jma/101.png', image_night: './image/data_source/jma/501.png'}
      '140': {weather: '晴時々雨で雷を伴う', image_day: './image/data_source/jma/102.png', image_night: './image/data_source/jma/502.png'}
      '160': {weather: '晴一時雪か雨', image_day: './image/data_source/jma/104.png', image_night: './image/data_source/jma/504.png'}
      '170': {weather: '晴時々雪か雨', image_day: './image/data_source/jma/104.png', image_night: './image/data_source/jma/504.png'}
      '181': {weather: '晴後雪か雨', image_day: './image/data_source/jma/115.png', image_night: './image/data_source/jma/515.png'}
      '200': {weather: '曇', image_day: './image/data_source/jma/200.png', image_night: './image/data_source/jma/200.png'}
      '201': {weather: '曇時々晴', image_day: './image/data_source/jma/201.png', image_night: './image/data_source/jma/601.png'}
      '202': {weather: '曇一時雨', image_day: './image/data_source/jma/202.png', image_night: './image/data_source/jma/202.png'}
      '203': {weather: '曇時々雨', image_day: './image/data_source/jma/202.png', image_night: './image/data_source/jma/202.png'}
      '204': {weather: '曇一時雪', image_day: './image/data_source/jma/204.png', image_night: './image/data_source/jma/204.png'}
      '205': {weather: '曇時々雪', image_day: './image/data_source/jma/204.png', image_night: './image/data_source/jma/204.png'}
      '206': {weather: '曇一時雨か雪', image_day: './image/data_source/jma/202.png', image_night: './image/data_source/jma/202.png'}
      '207': {weather: '曇時々雨か雪', image_day: './image/data_source/jma/202.png', image_night: './image/data_source/jma/202.png'}
      '208': {weather: '曇一時雨か雷雨', image_day: './image/data_source/jma/202.png', image_night: './image/data_source/jma/202.png'}
      '209': {weather: '霧', image_day: './image/data_source/jma/200.png', image_night: './image/data_source/jma/200.png'}
      '210': {weather: '曇後時々晴', image_day: './image/data_source/jma/210.png', image_night: './image/data_source/jma/610.png'}
      '211': {weather: '曇後晴', image_day: './image/data_source/jma/210.png', image_night: './image/data_source/jma/610.png'}
      '212': {weather: '曇後一時雨', image_day: './image/data_source/jma/212.png', image_night: './image/data_source/jma/212.png'}
      '213': {weather: '曇後時々雨', image_day: './image/data_source/jma/212.png', image_night: './image/data_source/jma/212.png'}
      '214': {weather: '曇後雨', image_day: './image/data_source/jma/212.png', image_night: './image/data_source/jma/212.png'}
      '215': {weather: '曇後一時雪', image_day: './image/data_source/jma/215.png', image_night: './image/data_source/jma/215.png'}
      '216': {weather: '曇後時々雪', image_day: './image/data_source/jma/215.png', image_night: './image/data_source/jma/215.png'}
      '217': {weather: '曇後雪', image_day: './image/data_source/jma/215.png', image_night: './image/data_source/jma/215.png'}
      '218': {weather: '曇後雨か雪', image_day: './image/data_source/jma/212.png', image_night: './image/data_source/jma/212.png'}
      '219': {weather: '曇後雨か雷雨', image_day: './image/data_source/jma/212.png', image_night: './image/data_source/jma/212.png'}
      '220': {weather: '曇朝夕一時雨', image_day: './image/data_source/jma/202.png', image_night: './image/data_source/jma/202.png'}
      '221': {weather: '曇朝の内一時雨', image_day: './image/data_source/jma/202.png', image_night: './image/data_source/jma/202.png'}
      '222': {weather: '曇夕方一時雨', image_day: './image/data_source/jma/212.png', image_night: './image/data_source/jma/212.png'}
      '223': {weather: '曇日中時々晴', image_day: './image/data_source/jma/201.png', image_night: './image/data_source/jma/601.png'}
      '224': {weather: '曇昼頃から雨', image_day: './image/data_source/jma/212.png', image_night: './image/data_source/jma/212.png'}
      '225': {weather: '曇夕方から雨', image_day: './image/data_source/jma/212.png', image_night: './image/data_source/jma/212.png'}
      '226': {weather: '曇夜は雨', image_day: './image/data_source/jma/212.png', image_night: './image/data_source/jma/212.png'}
      '228': {weather: '曇昼頃から雪', image_day: './image/data_source/jma/215.png', image_night: './image/data_source/jma/215.png'}
      '229': {weather: '曇夕方から雪', image_day: './image/data_source/jma/215.png', image_night: './image/data_source/jma/215.png'}
      '230': {weather: '曇夜は雪', image_day: './image/data_source/jma/215.png', image_night: './image/data_source/jma/215.png'}
      '231': {weather: '曇海上海岸は霧か霧雨', image_day: './image/data_source/jma/200.png', image_night: './image/data_source/jma/200.png'}
      '240': {weather: '曇時々雨で雷を伴う', image_day: './image/data_source/jma/202.png', image_night: './image/data_source/jma/202.png'}
      '250': {weather: '曇時々雪で雷を伴う', image_day: './image/data_source/jma/204.png', image_night: './image/data_source/jma/204.png'}
      '260': {weather: '曇一時雪か雨', image_day: './image/data_source/jma/204.png', image_night: './image/data_source/jma/204.png'}
      '270': {weather: '曇時々雪か雨', image_day: './image/data_source/jma/204.png', image_night: './image/data_source/jma/204.png'}
      '281': {weather: '曇後雪か雨', image_day: './image/data_source/jma/215.png', image_night: './image/data_source/jma/215.png'}
      '300': {weather: '雨', image_day: './image/data_source/jma/300.png', image_night: './image/data_source/jma/300.png'}
      '301': {weather: '雨時々晴', image_day: './image/data_source/jma/301.png', image_night: './image/data_source/jma/701.png'}
      '302': {weather: '雨時々止む', image_day: './image/data_source/jma/302.png', image_night: './image/data_source/jma/302.png'}
      '303': {weather: '雨時々雪', image_day: './image/data_source/jma/303.png', image_night: './image/data_source/jma/303.png'}
      '304': {weather: '雨か雪', image_day: './image/data_source/jma/300.png', image_night: './image/data_source/jma/300.png'}
      '306': {weather: '大雨', image_day: './image/data_source/jma/300.png', image_night: './image/data_source/jma/300.png'}
      '308': {weather: '雨で暴風を伴う', image_day: './image/data_source/jma/308.png', image_night: './image/data_source/jma/308.png'}
      '309': {weather: '雨一時雪', image_day: './image/data_source/jma/303.png', image_night: './image/data_source/jma/303.png'}
      '311': {weather: '雨後晴', image_day: './image/data_source/jma/311.png', image_night: './image/data_source/jma/711.png'}
      '313': {weather: '雨後曇', image_day: './image/data_source/jma/313.png', image_night: './image/data_source/jma/313.png'}
      '314': {weather: '雨後時々雪', image_day: './image/data_source/jma/314.png', image_night: './image/data_source/jma/314.png'}
      '315': {weather: '雨後雪', image_day: './image/data_source/jma/314.png', image_night: './image/data_source/jma/314.png'}
      '316': {weather: '雨か雪後晴', image_day: './image/data_source/jma/311.png', image_night: './image/data_source/jma/711.png'}
      '317': {weather: '雨か雪後曇', image_day: './image/data_source/jma/313.png', image_night: './image/data_source/jma/313.png'}
      '320': {weather: '朝の内雨後晴', image_day: './image/data_source/jma/311.png', image_night: './image/data_source/jma/711.png'}
      '321': {weather: '朝の内雨後曇', image_day: './image/data_source/jma/313.png', image_night: './image/data_source/jma/313.png'}
      '322': {weather: '雨朝晩一時雪', image_day: './image/data_source/jma/303.png', image_night: './image/data_source/jma/303.png'}
      '323': {weather: '雨昼頃から晴', image_day: './image/data_source/jma/311.png', image_night: './image/data_source/jma/711.png'}
      '324': {weather: '雨夕方から晴', image_day: './image/data_source/jma/311.png', image_night: './image/data_source/jma/711.png'}
      '325': {weather: '雨夜は晴', image_day: './image/data_source/jma/311.png', image_night: './image/data_source/jma/711.png'}
      '326': {weather: '雨夕方から雪', image_day: './image/data_source/jma/314.png', image_night: './image/data_source/jma/314.png'}
      '327': {weather: '雨夜は雪', image_day: './image/data_source/jma/314.png', image_night: './image/data_source/jma/314.png'}
      '328': {weather: '雨一時強く降る', image_day: './image/data_source/jma/300.png', image_night: './image/data_source/jma/300.png'}
      '329': {weather: '雨一時みぞれ', image_day: './image/data_source/jma/300.png', image_night: './image/data_source/jma/300.png'}
      '340': {weather: '雪か雨', image_day: './image/data_source/jma/400.png', image_night: './image/data_source/jma/400.png'}
      '350': {weather: '雨で雷を伴う', image_day: './image/data_source/jma/300.png', image_night: './image/data_source/jma/300.png'}
      '361': {weather: '雪か雨後晴', image_day: './image/data_source/jma/411.png', image_night: './image/data_source/jma/811.png'}
      '371': {weather: '雪か雨後曇', image_day: './image/data_source/jma/413.png', image_night: './image/data_source/jma/413.png'}
      '400': {weather: '雪', image_day: './image/data_source/jma/400.png', image_night: './image/data_source/jma/400.png'}
      '401': {weather: '雪時々晴', image_day: './image/data_source/jma/401.png', image_night: './image/data_source/jma/801.png'}
      '402': {weather: '雪時々止む', image_day: './image/data_source/jma/402.png', image_night: './image/data_source/jma/402.png'}
      '403': {weather: '雪時々雨', image_day: './image/data_source/jma/403.png', image_night: './image/data_source/jma/403.png'}
      '405': {weather: '大雪', image_day: './image/data_source/jma/400.png', image_night: './image/data_source/jma/400.png'}
      '406': {weather: '風雪強い', image_day: './image/data_source/jma/406.png', image_night: './image/data_source/jma/406.png'}
      '407': {weather: '暴風雪', image_day: './image/data_source/jma/406.png', image_night: './image/data_source/jma/406.png'}
      '409': {weather: '雪一時雨', image_day: './image/data_source/jma/403.png', image_night: './image/data_source/jma/403.png'}
      '411': {weather: '雪後晴', image_day: './image/data_source/jma/411.png', image_night: './image/data_source/jma/811.png'}
      '413': {weather: '雪後曇', image_day: './image/data_source/jma/413.png', image_night: './image/data_source/jma/413.png'}
      '414': {weather: '雪後雨', image_day: './image/data_source/jma/414.png', image_night: './image/data_source/jma/414.png'}
      '420': {weather: '朝の内雪後晴', image_day: './image/data_source/jma/411.png', image_night: './image/data_source/jma/811.png'}
      '421': {weather: '朝の内雪後曇', image_day: './image/data_source/jma/413.png', image_night: './image/data_source/jma/413.png'}
      '422': {weather: '雪昼頃から雨', image_day: './image/data_source/jma/414.png', image_night: './image/data_source/jma/414.png'}
      '423': {weather: '雪夕方から雨', image_day: './image/data_source/jma/414.png', image_night: './image/data_source/jma/414.png'}
      '425': {weather: '雪一時強く降る', image_day: './image/data_source/jma/400.png', image_night: './image/data_source/jma/400.png'}
      '426': {weather: '雪後みぞれ', image_day: './image/data_source/jma/400.png', image_night: './image/data_source/jma/400.png'}
      '427': {weather: '雪一時みぞれ', image_day: './image/data_source/jma/400.png', image_night: './image/data_source/jma/400.png'}
      '450': {weather: '雪で雷を伴う', image_day: './image/data_source/jma/400.png', image_night: './image/data_source/jma/400.png'}

